# This is the configuration file for Cloudflare Pages.
# It provides explicit instructions for the build environment.

name = "telegram-mini-app"

# This key is REQUIRED by Cloudflare Pages when a wrangler.toml is present.
# It must match the "Build output directory" in your Pages project settings.
pages_build_output_dir = ".cloudflare"

# This sets the compatibility date for the Workers runtime.
compatibility_date = "2024-07-18"

# This explicitly enables the Node.js compatibility flag.
compatibility_flags = ["nodejs_compat"]
