# This is the configuration file for Cloudflare Workers and Pages.
# It provides explicit instructions for the build environment.

name = "telegram-mini-app"
compatibility_date = "2025-07-18"

# This is the corrected syntax for compatibility flags.
# It should be at the top level, not under [vars].
compatibility_flags = ["nodejs_compat"]
